-- 코드를 입력하세요
SELECT a.FOOD_TYPE,a.REST_ID,a.REST_NAME,MAX(a.FAVORITES)
FROM REST_INFO a, REST_INFO b 
WHERE a.FOOD_TYPE=b.FOOD_TYPE
GROUP BY a.FOOD_TYPE,a.REST_ID,a.REST_NAME
HAVING MAX(a.FAVORITES)=MAX(b.FAVORITES) 
ORDER BY a.FOOD_TYPE DESC;