-- 코드를 입력하세요
SELECT U.USER_ID,U.NICKNAME,SUM(B.PRICE) as TOTAL_SALES
FROM USED_GOODS_USER U ,USED_GOODS_BOARD B
WHERE STATUS='DONE' AND
USER_ID = WRITER_ID
GROUP BY USER_ID,NICKNAME
HAVING SUM(PRICE)>=700000
ORDER BY TOTAL_SALES;