-- 코드를 입력하세요
SELECT EXTRACT(MONTH from TO_DATE(a.START_DATE, 'YYYY-MM-DD')) as M, a.CAR_ID,COUNT(a.CAR_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
WHERE a.CAR_ID in (Select b.CAR_ID
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY b
                   WHERE b.START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD') 
                   GROUP BY b.CAR_ID
                   HAVING COUNT(b.CAR_ID)>=5) 
    AND a.START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD') 

GROUP BY extract(MONTH from TO_DATE(a.START_DATE, 'YYYY-MM-DD')), a.CAR_ID
HAVING COUNT(a.CAR_ID)!=0
ORDER BY M ASC,a.CAR_ID DESC;


